### ISSUE TITLE
about config file and command!

### ISSUE THREAD

**Issue by sunnycqcn** [chmccarthy/Pangloss#1]
Hello,
Could you help me check the config file is correct? I try to run Pangloss.py with test dataset. However, I always get the error as following. I set the config file as following what you introduced. But I am not sure it is correct.
The attachment
[config.txt](https://github.com/chmccarthy/Pangloss/files/3687887/config.txt)

 is my config file.

./Pangloss.py: line 81:
Pangloss: A pipeline for pan-genome analysis of microbial eukaryotes.

Written by Charley McCarthy, Genome Evolution Lab, Department of Biology,
Maynooth University between 2017-2019 (Charley.McCarthy@nuim.ie).

See Pangloss/README.md for more information.

To-do:
    - Improve logging.

Recent changes:
    v0.9.1 (August 2019)
    - Fixes to how Pangloss reads in config file.
    - Made Pangloss.py executable.
    - Fixes to yn00 parsing.
    - Disabled tarballing prediction temp files because of how slow it seemed to be.
    - Other minor changes.

    v0.9.0 (June 2019)
    - Tested out InterProScan and GOATools pipelines.
    - Changed how UpSet plots are generated, now done through Cairo (on Mac at least).

    v0.8.0 (May 2019)
    - Rejigged when exactly amino acid, nucleotide and attribute datasets are concatenated.
    - Loads of changes to R scripts.
    - Fully implemented pangenome refinement using gap: No such file or directory
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
./Pangloss.py: line 87: from: command not found
./Pangloss.py: line 88: from: command not found
./Pangloss.py: line 89: from: command not found
./Pangloss.py: line 90: from: command not found
./Pangloss.py: line 91: from: command not found
./Pangloss.py: line 93: from: command not found
./Pangloss.py: line 94: from: command not found
./Pangloss.py: line 97: syntax error near unexpected token `('
./Pangloss.py: line 97: `def PanGuessHandler(ex_path, gm_path, tp_path, tl_path,'

**Comment by chmccarthy** [comment]
This is due to a pretty basic error on my part, there was no Python shebang line at the start of `Pangloss.py` so your OS was interpreting the file through the shell rather than through Python itself. Should be resolved with the latest commit e99fd9b3648ec511a79b742c4fb7617367b83eff where I've added `#!/usr/bin/env python` to the top of `Pangloss.py`. As for your config file, nothing looks out of the ordinary to me there. I'm going to mark this issue as closed but feel to comment if you're having issues further down the line.

**Comment by sunnycqcn** [comment]
Hello,
The above error have fixed. The yn00 path still looks some problem, although you have presented that it has been fixed. 
Could you help me check this error?
Thanks,
Fuyou


(Pangloss) [fuf@biocluster Test_Dataset]$ Pangloss.py --qc config.ini
  File "/home/AAFC-AAC/fuf/miniconda3/envs/Pangloss/bin/Pangloss.py", line 332
    print "{0}, {1} has unusual frameshift mutation and can't be run through yn00.".format(e, cluster)
                                                                                  ^
SyntaxError: invalid syntax

**Comment by chmccarthy** [comment]
I notice you're running Pangloss in miniconda3, which is Python3-based. Pangloss is Python2-based at the moment (it's what I was working in at the time of writing), so the fact that it uses the `print` statement rather than the `print()` function is what's causing the problem. I'll work on updating Pangloss to Python3 in the next few weeks once I have some downtime.

**Comment by sunnycqcn** [comment]
Hello,
I think this error is still about python environment set. My question is Pangloss.py only can run under Python2.7. I installed Python2.7 environment under miniconda3 with two ways, I got the error as following. 
**1.under funannotate environment with Python2.7**
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/Pangloss.py", line 630, in <module>
    main()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/Pangloss.py", line 585, in main
    PanOCTHandler(*panoct_default_args)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/Pangloss.py", line 284, in PanOCTHandler
    PanOCT.GenerateClusterFASTAs("genomes/genomes.txt")
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss/PanOCT.py", line 144, in GenerateClusterFASTAs
    core, acc = ParseMatchtable(matchtable)
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss/Tools.py", line 154, in ParseMatchtable
    clusters = reader(open(matchtable), delimiter="\t")
IOError: [Errno 2] No such file or directory: './panoct/matchtable.txt'
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/Pangloss.py", line 630, in <module>
    main()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/Pangloss.py", line 596, in main
    IPSHandler(ip_path)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/Pangloss.py", line 294, in IPSHandler
    GO.RunInterProScan("/gm_pred/sets/allprot.db", ips_path, cores)
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss/GO.py", line 32, in RunInterProScan
    "./go/ips.db", "-o", "./go/ips.output.tsv", "-f", "tsv", "-cpu", str(cores)])
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2. under python2.7 in miniconda3
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss.py", line 630, in <module>
    main()
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss.py", line 585, in main
    PanOCTHandler(*panoct_default_args)
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss.py", line 284, in PanOCTHandler
    PanOCT.GenerateClusterFASTAs("genomes/genomes.txt")
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss/PanOCT.py", line 144, in GenerateClusterFASTAs
    core, acc = ParseMatchtable(matchtable)
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss/Tools.py", line 154, in ParseMatchtable
    clusters = reader(open(matchtable), delimiter="\t")
IOError: [Errno 2] No such file or directory: './panoct/matchtable.txt'
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss.py", line 630, in <module>
    main()
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss.py", line 596, in main
    IPSHandler(ip_path)
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss.py", line 294, in IPSHandler
    GO.RunInterProScan("/gm_pred/sets/allprot.db", ips_path, cores)
  File "/home/AAFC-AAC/fuf/Pangloss/Pangloss/GO.py", line 32, in RunInterProScan
    "./go/ips.db", "-o", "./go/ips.output.tsv", "-f", "tsv", "-cpu", str(cores)])
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Thanks,
Fuyou

**Comment by chmccarthy** [comment]
Hi Fuyou,

The error you're getting is the same in both runs:

> clusters = reader(open(matchtable), delimiter="\t")
> IOError: [Errno 2] No such file or directory: './panoct/matchtable.txt'

In both cases Pangloss is looking for a file called "matchtable.txt" in the subfolder "panoct". This subfolder is for the output of panoct.pl, which runs pangenome analysis on your predicted protein sets. The error seems to imply that panoct.pl didn't run correctly or that organizing its output wasn't handled correctly, so maybe check to see that you can run panoct.pl in your environment. If you just want the predicted protein sets run Pangloss with the argument `--pred_only`.
